export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEM = 'GET_ITEM';

export const SET_LOADING = 'SET_LOADING';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_USER_CART = 'GET_USER_CART'

export const LOGOUT = 'LOGOUT'

//cart part
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
//cart part for server
export const REMOVE_ITEM_FROM_CART_SERVER = 'REMOVE_ITEM_FROM_CART_SERVER';
export const ADD_ITEM_TO_CART_SERVER = 'ADD_ITEM_TO_CART_SERVER';